INSERT INTO items (id, name, img, price)
VALUES (34, 'Abyssal Mask', 'https://www.mobafire.com/images/item/abyssal-mask.gif', 3000),
       (337, 'Adaptive Helm', 'https://www.mobafire.com/images/item/adaptive-helm.gif', 2800),
       (77, 'Aegis of the Legion', 'https://www.mobafire.com/images/item/aegis-of-the-legion.gif', 1100),
       (235, 'Aether Wisp', 'https://www.mobafire.com/images/item/aether-wisp.gif', 850),
       (21, 'Amplifying Tome', 'https://www.mobafire.com/images/item/amplifying-tome.gif', 435),
       (35, 'Archangel''s Staff', 'https://www.mobafire.com/images/item/archangels-staff.gif', 3200),
       (243, 'Ardent Censer', 'https://www.mobafire.com/images/item/ardent-censer.gif', 2300),
       (137, 'Athene''s Unholy Grail', 'https://www.mobafire.com/images/item/athenes-unholy-grail.gif', 2250),
       (17, 'B. F. Sword', 'https://www.mobafire.com/images/item/b-f-sword.gif', 1300),
       (284, 'Bami''s Cinder', 'https://www.mobafire.com/images/item/bamis-cinder.gif', 900),
       (76, 'Banshee''s Veil', 'https://www.mobafire.com/images/item/banshees-veil.gif', 3000),
       (37, 'Berserker''s Greaves', 'https://www.mobafire.com/images/item/berserkers-greaves.gif', 1100),
       (103, 'Bilgewater Cutlass', 'https://www.mobafire.com/images/item/bilgewater-cutlass.gif', 1600),
       (59, 'Black Cleaver', 'https://www.mobafire.com/images/item/black-cleaver.gif', 3000),
       (401, 'Black Mist Scythe', 'https://www.mobafire.com/images/item/black-mist-scythe.gif', 400),
       (250, 'Black Spear', 'https://www.mobafire.com/images/item/black-spear.gif', 0),
       (145, 'Blade of the Ruined King', 'https://www.mobafire.com/images/item/blade-of-the-ruined-king.gif', 3300),
       (9, 'Blasting Wand', 'https://www.mobafire.com/images/item/blasting-wand.gif', 850),
       (60, 'Bloodthirster', 'https://www.mobafire.com/images/item/bloodthirster.gif', 3500),
       (86, 'Boots of Mobility', 'https://www.mobafire.com/images/item/boots-of-mobility.gif', 1000),
       (1, 'Boots of Speed', 'https://www.mobafire.com/images/item/boots-of-speed.gif', 300),
       (38, 'Boots of Swiftness', 'https://www.mobafire.com/images/item/boots-of-swiftness.gif', 900),
       (341, 'Bramble Vest', 'https://www.mobafire.com/images/item/bramble-vest.gif', 1000),
       (387, 'Broken Stopwatch', 'https://www.mobafire.com/images/item/broken-stopwatch.gif', 600),
       (405, 'Bulwark of the Mountain', 'https://www.mobafire.com/images/item/bulwark-of-the-mountain.gif', 400),
       (39, 'Catalyst of Aeons', 'https://www.mobafire.com/images/item/catalyst-of-aeons.gif', 1100),
       (309, 'Caulfield''s Warhammer', 'https://www.mobafire.com/images/item/caulfields-warhammer.gif', 1100),
       (13, 'Chain Vest', 'https://www.mobafire.com/images/item/chain-vest.gif', 800),
       (45, 'Chalice of Harmony', 'https://www.mobafire.com/images/item/chalice-of-harmony.gif', 800),
       (349, 'Circlet of the Iron Solari', 'https://www.mobafire.com/images/item/circlet-of-the-iron-solari.gif', 2200),
       (8, 'Cloak of Agility', 'https://www.mobafire.com/images/item/cloak-of-agility.gif', 600),
       (12, 'Cloth Armor', 'https://www.mobafire.com/images/item/cloth-armor.gif', 300),
       (388, 'Commencing Stopwatch', 'https://www.mobafire.com/images/item/commencing-stopwatch.gif', 0),
       (332, 'Control Ward', 'https://www.mobafire.com/images/item/control-ward.gif', 75),
       (307, 'Corrupting Potion', 'https://www.mobafire.com/images/item/corrupting-potion.gif', 500),
       (251, 'Crystalline Bracer', 'https://www.mobafire.com/images/item/crystalline-bracer.gif', 650),
       (304, 'Cull', 'https://www.mobafire.com/images/item/cull.gif', 450),
       (18, 'Dagger', 'https://www.mobafire.com/images/item/dagger.gif', 300),
       (303, 'Dark Seal', 'https://www.mobafire.com/images/item/dark-seal.gif', 350),
       (287, 'Dead Man''s Plate', 'https://www.mobafire.com/images/item/dead-mans-plate.gif', 2900),
       (308, 'Death''s Dance', 'https://www.mobafire.com/images/item/deaths-dance.gif', 3500),
       (290, 'Death''s Daughter', 'https://www.mobafire.com/images/item/deaths-daughter.gif', 500),
       (24, 'Doran''s Blade', 'https://www.mobafire.com/images/item/dorans-blade.gif', 450),
       (25, 'Doran''s Ring', 'https://www.mobafire.com/images/item/dorans-ring.gif', 400),
       (23, 'Doran''s Shield', 'https://www.mobafire.com/images/item/dorans-shield.gif', 450),
       (322, 'Duskblade of Draktharr', 'https://www.mobafire.com/images/item/duskblade-of-draktharr.gif', 2900),
       (333, 'Edge of Night', 'https://www.mobafire.com/images/item/edge-of-night.gif', 2900),
       (254, 'Elixir of Iron', 'https://www.mobafire.com/images/item/elixir-of-iron.gif', 500),
       (256, 'Elixir of Sorcery', 'https://www.mobafire.com/images/item/elixir-of-sorcery.gif', 500),
       (257, 'Elixir of Wrath', 'https://www.mobafire.com/images/item/elixir-of-wrath.gif', 500),
       (326, 'Enchantment: Bloodrazor', 'https://www.mobafire.com/images/item/enchantment-bloodrazor.gif', 1625),
       (285, 'Enchantment: Cinderhulk', 'https://www.mobafire.com/images/item/enchantment-cinderhulk.gif', 1500),
       (318, 'Enchantment: Runic Echoes', 'https://www.mobafire.com/images/item/enchantment-runic-echoes.gif', 1625),
       (281, 'Enchantment: Warrior', 'https://www.mobafire.com/images/item/enchantment-warrior.gif', 1625),
       (244, 'Essence Reaver', 'https://www.mobafire.com/images/item/essence-reaver.gif', 3300),
       (87, 'Executioner''s Calling', 'https://www.mobafire.com/images/item/executioners-calling.gif', 800),
       (390, 'Eye of the Herald', 'https://www.mobafire.com/images/item/eye-of-the-herald.gif', 0),
       (2, 'Faerie Charm', 'https://www.mobafire.com/images/item/faerie-charm.gif', 125),
       (312, 'Farsight Alteration', 'https://www.mobafire.com/images/item/farsight-alteration.gif', 0),
       (79, 'Fiendish Codex', 'https://www.mobafire.com/images/item/fiendish-codex.gif', 900),
       (292, 'Fire At Will', 'https://www.mobafire.com/images/item/fire-at-will.gif', 500),
       (237, 'Forbidden Idol', 'https://www.mobafire.com/images/item/forbidden-idol.gif', 850),
       (342, 'Forgefire Cape', 'https://www.mobafire.com/images/item/forgefire-cape.gif', 2900),
       (72, 'Frostfang', 'https://www.mobafire.com/images/item/frostfang.gif', 850),
       (391, 'Frozen Fist', 'https://www.mobafire.com/images/item/frozen-fist.gif', 2700),
       (81, 'Frozen Heart', 'https://www.mobafire.com/images/item/frozen-heart.gif', 2700),
       (41, 'Frozen Mallet', 'https://www.mobafire.com/images/item/frozen-mallet.gif', 3100),
       (338, 'Gargoyle Stoneplate', 'https://www.mobafire.com/images/item/gargoyle-stoneplate.gif', 2500),
       (6, 'Giant''s Belt', 'https://www.mobafire.com/images/item/giants-belt.gif', 1000),
       (42, 'Glacial Shroud', 'https://www.mobafire.com/images/item/glacial-shroud.gif', 900),
       (43, 'Guardian Angel', 'https://www.mobafire.com/images/item/guardian-angel.gif', 2800),
       (331, 'Guardian''s Hammer', 'https://www.mobafire.com/images/item/guardians-hammer.gif', 950),
       (180, 'Guardian''s Horn', 'https://www.mobafire.com/images/item/guardians-horn.gif', 950),
       (330, 'Guardian''s Orb', 'https://www.mobafire.com/images/item/guardians-orb.gif', 950),
       (88, 'Guinsoo''s Rageblade', 'https://www.mobafire.com/images/item/guinsoos-rageblade.gif', 3100),
       (400, 'Harrowing Crescent', 'https://www.mobafire.com/images/item/harrowing-crescent.gif', 400),
       (99, 'Haunting Guise', 'https://www.mobafire.com/images/item/haunting-guise.gif', 1600),
       (27, 'Health Potion', 'https://www.mobafire.com/images/item/health-potion.gif', 50),
       (247, 'Hex Core MK-1', 'https://www.mobafire.com/images/item/hex-core-mk-1.gif', 1150),
       (248, 'Hex Core MK-2', 'https://www.mobafire.com/images/item/hex-core-mk-2.gif', 2150),
       (112, 'Hexdrinker', 'https://www.mobafire.com/images/item/hexdrinker.gif', 1300),
       (324, 'Hextech GLP-800', 'https://www.mobafire.com/images/item/hextech-glp-800.gif', 2800),
       (104, 'Hextech Gunblade', 'https://www.mobafire.com/images/item/hextech-gunblade.gif', 3400),
       (325, 'Hextech Protobelt-01', 'https://www.mobafire.com/images/item/hextech-protobelt-01.gif', 2500),
       (105, 'Hextech Revolver', 'https://www.mobafire.com/images/item/hextech-revolver.gif', 1050),
       (151, 'Hunter''s Machete', 'https://www.mobafire.com/images/item/hunters-machete.gif', 350),
       (298, 'Hunter''s Talisman', 'https://www.mobafire.com/images/item/hunters-talisman.gif', 350),
       (150, 'Iceborn Gauntlet', 'https://www.mobafire.com/images/item/iceborn-gauntlet.gif', 2700),
       (343, 'Infernal Mask', 'https://www.mobafire.com/images/item/infernal-mask.gif', 2900),
       (46, 'Infinity Edge', 'https://www.mobafire.com/images/item/infinity-edge.gif', 3400),
       (113, 'Ionian Boots of Lucidity', 'https://www.mobafire.com/images/item/ionian-boots-of-lucidity.gif', 900),
       (310, 'Jaurim''s Fist', 'https://www.mobafire.com/images/item/jaurims-fist.gif', 1200),
       (110, 'Kindlegem', 'https://www.mobafire.com/images/item/kindlegem.gif', 800),
       (293, 'Kircheis Shard', 'https://www.mobafire.com/images/item/kircheis-shard.gif', 700),
       (334, 'Knight''s Vow', 'https://www.mobafire.com/images/item/knights-vow.gif', 2200),
       (48, 'Last Whisper', 'https://www.mobafire.com/images/item/last-whisper.gif', 1450),
       (153, 'Liandry''s Torment', 'https://www.mobafire.com/images/item/liandrys-torment.gif', 3100),
       (74, 'Lich Bane', 'https://www.mobafire.com/images/item/lich-bane.gif', 3200),
       (135, 'Locket of the Iron Solari', 'https://www.mobafire.com/images/item/locket-of-the-iron-solari.gif', 2200),
       (15, 'Long Sword', 'https://www.mobafire.com/images/item/long-sword.gif', 350),
       (296, 'Lord Dominik''s Regards', 'https://www.mobafire.com/images/item/lord-dominiks-regards.gif', 2800),
       (323, 'Lost Chapter', 'https://www.mobafire.com/images/item/lost-chapter.gif', 1300),
       (283, 'Luden''s Echo', 'https://www.mobafire.com/images/item/ludens-echo.gif', 3200),
       (392, 'Luden''s Pulse', 'https://www.mobafire.com/images/item/ludens-pulse.gif', 3200),
       (109, 'Manamune', 'https://www.mobafire.com/images/item/manamune.gif', 2400),
       (136, 'Maw of Malmortius', 'https://www.mobafire.com/images/item/maw-of-malmortius.gif', 3250),
       (50, 'Mejai''s Soulstealer', 'https://www.mobafire.com/images/item/mejais-soulstealer.gif', 1400),
       (154, 'Mercurial Scimitar', 'https://www.mobafire.com/images/item/mercurial-scimitar.gif', 3500),
       (82, 'Mercury''s Treads', 'https://www.mobafire.com/images/item/mercurys-treads.gif', 1100),
       (393, 'Might of the Ruined King', 'https://www.mobafire.com/images/item/might-of-the-ruined-king.gif', 3300),
       (155, 'Mikael''s Crucible', 'https://www.mobafire.com/images/item/mikaels-crucible.gif', 2100),
       (352, 'Minion Dematerializer', 'https://www.mobafire.com/images/item/minion-dematerializer.gif', 0),
       (344, 'Molten Edge', 'https://www.mobafire.com/images/item/molten-edge.gif', 3400),
       (156, 'Morellonomicon', 'https://www.mobafire.com/images/item/morellonomicon.gif', 3000),
       (297, 'Mortal Reminder', 'https://www.mobafire.com/images/item/mortal-reminder.gif', 2800),
       (157, 'Muramana', 'https://www.mobafire.com/images/item/muramana.gif', 2100),
       (84, 'Nashor''s Tooth', 'https://www.mobafire.com/images/item/nashors-tooth.gif', 3000),
       (106, 'Needlessly Large Rod', 'https://www.mobafire.com/images/item/needlessly-large-rod.gif', 1250),
       (26, 'Negatron Cloak', 'https://www.mobafire.com/images/item/negatron-cloak.gif', 720),
       (53, 'Ninja Tabi', 'https://www.mobafire.com/images/item/ninja-tabi.gif', 1100),
       (14, 'Null-Magic Mantle', 'https://www.mobafire.com/images/item/null-magic-mantle.gif', 450),
       (366, 'Oblivion Orb', 'https://www.mobafire.com/images/item/oblivion-orb.gif', 1600),
       (345, 'Obsidian Cleaver', 'https://www.mobafire.com/images/item/obsidian-cleaver.gif', 3000),
       (313, 'Oracle Lens', 'https://www.mobafire.com/images/item/oracle-lens.gif', 0),
       (129, 'Oracle''s Extract', 'https://www.mobafire.com/images/item/oracles-extract.gif', 300),
       (404, 'Pauldrons of Whiterock', 'https://www.mobafire.com/images/item/pauldrons-of-whiterock.gif', 400),
       (249, 'Perfect Hex Core', 'https://www.mobafire.com/images/item/perfect-hex-core.gif', 3000),
       (51, 'Phage', 'https://www.mobafire.com/images/item/phage.gif', 1250),
       (52, 'Phantom Dancer', 'https://www.mobafire.com/images/item/phantom-dancer.gif', 2600),
       (16, 'Pickaxe', 'https://www.mobafire.com/images/item/pickaxe.gif', 875),
       (233, 'Poro-Snax', 'https://www.mobafire.com/images/item/poro-snax.gif', 0),
       (246, 'Prototype Hex Core', 'https://www.mobafire.com/images/item/prototype-hex-core.gif', 0),
       (94, 'Quicksilver Sash', 'https://www.mobafire.com/images/item/quicksilver-sash.gif', 1300),
       (115, 'Rabadon''s Deathcap', 'https://www.mobafire.com/images/item/rabadons-deathcap.gif', 3600),
       (346, 'Rabadon''s Deathcrown', 'https://www.mobafire.com/images/item/rabadons-deathcrown.gif', 3600),
       (291, 'Raise Morale', 'https://www.mobafire.com/images/item/raise-morale.gif', 500),
       (102, 'Randuin''s Omen', 'https://www.mobafire.com/images/item/randuins-omen.gif', 2900),
       (294, 'Rapid Firecannon', 'https://www.mobafire.com/images/item/rapid-firecannon.gif', 2600),
       (159, 'Ravenous Hydra', 'https://www.mobafire.com/images/item/ravenous-hydra.gif', 3500),
       (19, 'Recurve Bow', 'https://www.mobafire.com/images/item/recurve-bow.gif', 1000),
       (336, 'Redemption', 'https://www.mobafire.com/images/item/redemption.gif', 2100),
       (305, 'Refillable Potion', 'https://www.mobafire.com/images/item/refillable-potion.gif', 150),
       (4, 'Rejuvenation Bead', 'https://www.mobafire.com/images/item/rejuvenation-bead.gif', 150),
       (186, 'Relic Shield', 'https://www.mobafire.com/images/item/relic-shield.gif', 400),
       (253, 'Righteous Glory', 'https://www.mobafire.com/images/item/righteous-glory.gif', 2650),
       (44, 'Rod of Ages', 'https://www.mobafire.com/images/item/rod-of-ages.gif', 2600),
       (11, 'Ruby Crystal', 'https://www.mobafire.com/images/item/ruby-crystal.gif', 400),
       (161, 'Runaan''s Hurricane', 'https://www.mobafire.com/images/item/runaans-hurricane.gif', 2600),
       (403, 'Runesteel Spaulders', 'https://www.mobafire.com/images/item/runesteel-spaulders.gif', 400),
       (85, 'Rylai''s Crystal Scepter', 'https://www.mobafire.com/images/item/rylais-crystal-scepter.gif', 2600),
       (348, 'Salvation', 'https://www.mobafire.com/images/item/salvation.gif', 2100),
       (130, 'Sanguine Blade', 'https://www.mobafire.com/images/item/sanguine-blade.gif', 3100),
       (10, 'Sapphire Crystal', 'https://www.mobafire.com/images/item/sapphire-crystal.gif', 350),
       (179, 'Seeker''s Armguard', 'https://www.mobafire.com/images/item/seekers-armguard.gif', 1100),
       (163, 'Seraph''s Embrace', 'https://www.mobafire.com/images/item/seraphs-embrace.gif', 3200),
       (311, 'Serrated Dirk', 'https://www.mobafire.com/images/item/serrated-dirk.gif', 1100),
       (398, 'Shard of True Ice', 'https://www.mobafire.com/images/item/shard-of-true-ice.gif', 400),
       (55, 'Sheen', 'https://www.mobafire.com/images/item/sheen.gif', 1050),
       (379, 'Shurelya''s Reverie', 'https://www.mobafire.com/images/item/shurelyas-reverie.gif', 2050),
       (260, 'Skirmisher''s Sabre', 'https://www.mobafire.com/images/item/skirmishers-sabre.gif', 1000),
       (329, 'Skirmisher''s Sabre - Bloodrazor',
        'https://www.mobafire.com/images/item/skirmishers-sabre-bloodrazor.gif', 2625),
       (271, 'Skirmisher''s Sabre - Cinderhulk',
        'https://www.mobafire.com/images/item/skirmishers-sabre-cinderhulk.gif', 2500),
       (320, 'Skirmisher''s Sabre - Runic Echoes',
        'https://www.mobafire.com/images/item/skirmishers-sabre-runic-echoes.gif', 2500),
       (273, 'Skirmisher''s Sabre - Warrior', 'https://www.mobafire.com/images/item/skirmishers-sabre-warrior.gif',
        2625),
       (353, 'Slightly Magical Boots', 'https://www.mobafire.com/images/item/slightly-magical-boots.gif', 0),
       (40, 'Sorcerer''s Shoes', 'https://www.mobafire.com/images/item/sorcerers-shoes.gif', 1100),
       (399, 'Spectral Sickle', 'https://www.mobafire.com/images/item/spectral-sickle.gif', 400),
       (182, 'Spectre''s Cowl', 'https://www.mobafire.com/images/item/spectres-cowl.gif', 1200),
       (367, 'Spellbinder', 'https://www.mobafire.com/images/item/spellbinder.gif', 2900),
       (183, 'Spellthief''s Edge', 'https://www.mobafire.com/images/item/spellthiefs-edge.gif', 400),
       (56, 'Spirit Visage', 'https://www.mobafire.com/images/item/spirit-visage.gif', 2800),
       (261, 'Stalker''s Blade', 'https://www.mobafire.com/images/item/stalkers-blade.gif', 1000),
       (328, 'Stalker''s Blade - Bloodrazor', 'https://www.mobafire.com/images/item/stalkers-blade-bloodrazor.gif',
        2625),
       (275, 'Stalker''s Blade - Cinderhulk', 'https://www.mobafire.com/images/item/stalkers-blade-cinderhulk.gif',
        2500),
       (321, 'Stalker''s Blade - Runic Echoes', 'https://www.mobafire.com/images/item/stalkers-blade-runic-echoes.gif',
        2500),
       (277, 'Stalker''s Blade - Warrior', 'https://www.mobafire.com/images/item/stalkers-blade-warrior.gif', 2625),
       (169, 'Statikk Shiv', 'https://www.mobafire.com/images/item/statikk-shiv.gif', 2600),
       (402, 'Steel Shoulderguards', 'https://www.mobafire.com/images/item/steel-shoulderguards.gif', 400),
       (288, 'Sterak''s Gage', 'https://www.mobafire.com/images/item/steraks-gage.gif', 3200),
       (75, 'Stinger', 'https://www.mobafire.com/images/item/stinger.gif', 1100),
       (351, 'Stopwatch', 'https://www.mobafire.com/images/item/stopwatch.gif', 650),
       (384, 'Stormrazor', 'https://www.mobafire.com/images/item/stormrazor.gif', 3200),
       (57, 'Sunfire Cape', 'https://www.mobafire.com/images/item/sunfire-cape.gif', 2750),
       (71, 'Targon''s Buckler', 'https://www.mobafire.com/images/item/targons-buckler.gif', 400),
       (58, 'Tear of the Goddess', 'https://www.mobafire.com/images/item/tear-of-the-goddess.gif', 850),
       (61, 'Thornmail', 'https://www.mobafire.com/images/item/thornmail.gif', 2900),
       (62, 'Tiamat', 'https://www.mobafire.com/images/item/tiamat.gif', 1325),
       (289, 'Titanic Hydra', 'https://www.mobafire.com/images/item/titanic-hydra.gif', 3500),
       (372, 'Total Biscuit of Everlasting Will',
        'https://www.mobafire.com/images/item/total-biscuit-of-everlasting-will.gif', 0),
       (63, 'Trinity Force', 'https://www.mobafire.com/images/item/trinity-force.gif', 3733),
       (347, 'Trinity Fusion', 'https://www.mobafire.com/images/item/trinity-fusion.gif', 3733),
       (171, 'Twin Shadows', 'https://www.mobafire.com/images/item/twin-shadows.gif', 2400),
       (397, 'Umbral Glaive', 'https://www.mobafire.com/images/item/umbral-glaive.gif', 2400),
       (22, 'Vampiric Scepter', 'https://www.mobafire.com/images/item/vampiric-scepter.gif', 900),
       (98, 'Void Staff', 'https://www.mobafire.com/images/item/void-staff.gif', 2650),
       (64, 'Warden''s Mail', 'https://www.mobafire.com/images/item/wardens-mail.gif', 1000),
       (188, 'Warding Totem', 'https://www.mobafire.com/images/item/warding-totem.gif', 0),
       (65, 'Warmog''s Armor', 'https://www.mobafire.com/images/item/warmogs-armor.gif', 2850),
       (68, 'Wit''s End', 'https://www.mobafire.com/images/item/wits-end.gif', 2900),
       (101, 'Youmuu''s Ghostblade', 'https://www.mobafire.com/images/item/youmuus-ghostblade.gif', 2900),
       (394, 'Youmuu''s Wraithblade', 'https://www.mobafire.com/images/item/youmuus-wraithblade.gif', 2900),
       (66, 'Zeal', 'https://www.mobafire.com/images/item/zeal.gif', 1400),
       (339, 'Zeke''s Convergence', 'https://www.mobafire.com/images/item/zekes-convergence.gif', 2250),
       (114, 'Zhonya''s Hourglass', 'https://www.mobafire.com/images/item/zhonyas-hourglass.gif', 2900),
       (350, 'Zhonya''s Paradox', 'https://www.mobafire.com/images/item/zhonyas-paradox.gif', 2900)
        